export const theme=
{
    "styles": {
        "body": "bg-gray-50 text-gray-900 font-sans leading-normal",
        "header": "bg-gradient-to-r from-teal-500 to-cyan-600 text-white py-5 shadow-lg",
        "nav": "flex justify-between max-w-6xl py-5 px-5",
        "navItem": "hover:text-teal-300 transition duration-300 px-4 py-2 font-semibold text-lg",
        "hero": "bg-cover bg-center h-80 flex items-center justify-center text-white text-center relative",
        "heroTitle": "text-6xl font-extra-bold mb-2 drop-shadow-lg",
        "heroSubtitle": "text-2xl mb-5 font-medium",
        "productGrid": " static ml-64 pt-[80px] h-full grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 p-6",
        "productCard": "bg-white rounded-lg shadow-lg transition-transform duration-300 transform hover:scale-105 overflow-hidden",
        "productImage": "rounded-t-lg w-full h-60 object-cover",
        "productInfo": "p-4 text-center",
        "productTitle": "text-xl font-bold mb-2 text-gray-800",
        "productPrice": "text-xl text-teal-600 font-semibold mb-4",
        "button": "bg-teal-600 text-white px-5 py-2 rounded-lg shadow-lg hover:bg-teal-500 transition-colors duration-300",
        "buttonDisabled": "bg-gray-300 cursor-not-allowed rounded-lg px-5 py-2 shadow",
        "footer": "bg-gray-800 text-white text-center py-6",
        "footerLink": "hover:underline transition duration-300",
        "input": "border border-gray-300 rounded-lg p-3 w-full focus:outline-none focus:ring-2 focus:ring-teal-500 transition duration-300",
        "inputError": "border-red-600 focus:ring-red-500",
        "textarea": "border border-gray-300 rounded-lg p-3 w-full focus:outline-none focus:ring-2 focus:ring-teal-500 transition duration-300",
        "select": "border border-gray-300 rounded-lg p-3 w-full focus:outline-none focus:ring-2 focus:ring-teal-500 transition duration-300",
        "sidebar": "col-span-1 row-start-2 row-end-6  mt-[100px] ml-4 bg-white shadow-md rounded-lg w-64 h-full fixed ",
        "sidebarTitle": "text-lg font-bold mb-2",
        "filterGroup": "mb-4",
        "filterLabel": "font-semibold text-gray-700 mb-1",
        "filterCheckbox": "flex items-center",
        "filterCheckboxInput": "mr-2",
        "filterCheckboxLabel": "text-gray-700",
        "priceRange": "flex flex-col space-y-2",
        "priceLabel": "text-gray-600 mb-1",
        "priceInput": "border border-gray-300 rounded-lg p-2 focus:outline-none focus:ring-2 focus:ring-teal-500",
        "applyFilterButton": "bg-teal-600 text-white px-4 py-2 rounded-lg w-full hover:bg-teal-500 transition duration-300",
        "cardBadge": "absolute top-0 left-0 bg-red-600 text-white text-xs font-bold rounded-full px-2 py-1",
        "highlight": "bg-yellow-100 border-l-4 border-yellow-400 p-3 rounded-md shadow",
        "formContainer": "max-w-md mx-auto p-4 bg-white rounded-lg shadow-lg",
        "formTitle": "text-2xl font-bold text-center mb-4",
        "formGroup": "mb-4",
        "formLabel": "block text-gray-700 font-medium mb-2",
        "formSubmit": "bg-teal-600 text-white px-6 py-2 rounded-lg w-full hover:bg-teal-500 transition duration-300",
        "banner": "bg-teal-100 border-l-4 border-teal-500 p-4 mb-4",
        "bannerTitle": "font-bold text-gray-800",
        "bannerText": "text-gray-700",
        "searchInput": "border border-gray-300 rounded-lg p-3 w-full focus:outline-none focus:ring-2 focus:ring-teal-500 mb-4"
}
}
